from __future__ import annotations

import logging
import time
from typing import ClassVar

import numpy as np
from scipy.integrate import solve_ivp

from numen.compiler.flatten import CompiledCallback, CompiledSpec, DxBuffer
from numen.bridge.runtime import SolveResult
from numen.errors import check_backend_features, check_python_fns

_log = logging.getLogger("numen.backend.scipy")

_TSTOP_MERGE_TOL = 1e-6   # merge tstops within 1 µs to avoid near-zero segments

_EXPLICIT_SOLVERS = {"RK23", "RK45", "DOP853", "LSODA"}


def _build_tstop_callbacks(
    callbacks: list[CompiledCallback],
    tspan: tuple[float, float],
) -> list[tuple[float, list[CompiledCallback]]]:
    """Build a sorted list of (tstop, [callbacks]) with near-coincident times merged.

    Times are generated by enumeration (t0 + k*dt), not by runtime float comparison,
    so each callback is attached to its tstop at generation time.  Tstops within
    _TSTOP_MERGE_TOL are collapsed to the earlier one; all callbacks for the merged
    group fire together.
    """
    t0, tf = tspan
    raw: dict[float, list[CompiledCallback]] = {}
    for cb in callbacks:
        t = t0 + cb.dt
        while t <= tf + 1e-12:
            key = round(t, 12)
            raw.setdefault(key, []).append(cb)
            t += cb.dt

    merged: list[tuple[float, list[CompiledCallback]]] = []
    for t_raw in sorted(raw):
        cbs = raw[t_raw]
        if merged and abs(t_raw - merged[-1][0]) < _TSTOP_MERGE_TOL:
            merged[-1][1].extend(cbs)
        else:
            merged.append((t_raw, list(cbs)))
    return merged


def _build_tstops(discrete_dts: list[float], tspan: tuple[float, float]) -> list[float]:
    t0, tf = tspan
    times: set[float] = set()
    for dt in discrete_dts:
        t = t0 + dt
        while t <= tf + 1e-12:
            times.add(round(t, 12))
            t += dt
    return sorted(times)


class ScipyBackend:
    """Pure-Python solver backend using scipy solve_ivp. Good for development and testing."""

    supported_features: ClassVar[frozenset[str]] = frozenset({
        "vector_fields",
        "discrete_fields",
        "continuous_fields",
        "control_callbacks",
    })

    def __init__(self, method: str = "RK45", rtol: float = 1e-6, atol: float = 1e-8,
                 dtmax: float | None = None, dtsave: float | None = None,
                 n_save_points: int = 0):
        if n_save_points > 0 and dtsave is not None:
            raise ValueError("Specify either n_save_points or dtsave, not both.")
        self.method = method
        self.rtol = rtol
        self.atol = atol
        self.dtmax = dtmax
        self.dtsave = dtsave
        self.n_save_points = n_save_points

    def solve(
        self,
        compiled_spec: CompiledSpec,
        tspan: tuple[float, float],
        t_eval: "np.ndarray | None" = None,
        progress: bool = False,
    ) -> SolveResult:
        check_backend_features(compiled_spec, "ScipyBackend", self.supported_features)
        check_python_fns(compiled_spec, "ScipyBackend")

        _log.debug(
            "solve: state_size=%d param_size=%d tspan=%s method=%s rtol=%g atol=%g",
            compiled_spec.state_size, compiled_spec.param_size,
            tspan, self.method, self.rtol, self.atol,
        )

        # Validate callbacks have python_fn
        cb_missing = [c.name for c in compiled_spec.compiled_callbacks if c.python_fn is None]
        if cb_missing:
            raise ValueError(
                f"ScipyBackend: callbacks missing python_fn: {cb_missing}\n"
                f"Declare 'python_fn: ClassVar = staticmethod(your_fn)' on the Callback class."
            )

        if compiled_spec.compiled_callbacks:
            return self._solve_segmented(compiled_spec, tspan, t_eval, progress)
        return self._solve_simple(compiled_spec, tspan, t_eval, progress)

    # ------------------------------------------------------------------
    # Simple path (no callbacks) — single solve_ivp call
    # ------------------------------------------------------------------

    def _solve_simple(
        self,
        compiled_spec: CompiledSpec,
        tspan: tuple[float, float],
        t_eval: "np.ndarray | None",
        progress: bool,
    ) -> SolveResult:
        p = np.array(compiled_spec.p)
        tstops = _build_tstops(compiled_spec.discrete_dts, tspan)
        t0_sim, tf_sim = tspan

        def rhs(t: float, x: np.ndarray) -> np.ndarray:
            dx = DxBuffer(np.zeros_like(x))
            for sys in compiled_spec.systems:
                sys.python_fn(dx, x, p, t, compiled_spec, sys)
            return dx.array

        if progress:
            rhs = _wrap_rhs_progress(rhs, t0_sim, tf_sim)

        t_eval = _apply_save_density(t_eval, tspan, self.dtsave, self.n_save_points)
        dense_eval = _merge_t_eval(t_eval, tstops)

        kw: dict = dict(method=self.method, t_eval=dense_eval, rtol=self.rtol, atol=self.atol)
        if self.dtmax is not None:
            kw["max_step"] = self.dtmax

        t0_wall = time.perf_counter()
        try:
            sol = solve_ivp(rhs, tspan, compiled_spec.x0, **kw)
        finally:
            if progress:
                _close_rhs_progress(rhs)

        elapsed_ms = (time.perf_counter() - t0_wall) * 1000
        if not sol.success:
            _log.error("solve failed after %.0f ms: %s", elapsed_ms, sol.message)
            raise RuntimeError(f"Solver failed: {sol.message}")

        _log.debug("solve done in %.1f ms, %d steps", elapsed_ms, len(sol.t))
        return SolveResult(t=sol.t, x=sol.y)

    # ------------------------------------------------------------------
    # Segmented path (with callbacks)
    # ------------------------------------------------------------------

    def _solve_segmented(
        self,
        compiled_spec: CompiledSpec,
        tspan: tuple[float, float],
        t_eval: "np.ndarray | None",
        progress: bool,
    ) -> SolveResult:
        p = np.array(compiled_spec.p)
        t0_sim, tf_sim = tspan

        t_eval = _apply_save_density(t_eval, tspan, self.dtsave, self.n_save_points)

        # Build the callback fire schedule
        cb_schedule = _build_tstop_callbacks(compiled_spec.compiled_callbacks, tspan)
        # Also include DiscreteField tstops (no callback, just save points)
        disc_tstops = set(_build_tstops(compiled_spec.discrete_dts, tspan))

        # All segment boundaries = callback tstops ∪ disc tstops ∪ [tf]
        cb_times = {t for t, _ in cb_schedule}
        all_boundaries = sorted(cb_times | disc_tstops | {tf_sim})

        def rhs(t: float, x: np.ndarray) -> np.ndarray:
            dx = DxBuffer(np.zeros_like(x))
            for sys in compiled_spec.systems:
                sys.python_fn(dx, x, p, t, compiled_spec, sys)
            return dx.array

        # Build a lookup from tstop → callbacks (only for cb_schedule entries)
        cb_at: dict[float, list[CompiledCallback]] = {t: cbs for t, cbs in cb_schedule}

        t_cur = t0_sim
        x_cur = np.array(compiled_spec.x0, dtype=float)
        all_t: list[np.ndarray] = []
        all_x: list[np.ndarray] = []  # each entry shape (state_size, n_steps_in_segment)

        t0_wall = time.perf_counter()

        if progress:
            try:
                from tqdm.auto import tqdm
                pbar = tqdm(
                    total=tf_sim - t0_sim, unit="s", desc="scipy",
                    bar_format="{desc}: {percentage:.0f}%|{bar}| {n:.3g}/{total:.3g} s  [{elapsed}<{remaining}]",
                    dynamic_ncols=True,
                )
            except ImportError:
                pbar = None
        else:
            pbar = None

        for t_stop in all_boundaries:
            if t_stop <= t_cur + 1e-15:
                continue

            # t_eval points inside this segment
            if t_eval is not None:
                seg_eval_mask = (t_eval > t_cur) & (t_eval <= t_stop)
                seg_eval = np.sort(np.unique(np.concatenate([t_eval[seg_eval_mask], [t_stop]])))
            else:
                seg_eval = np.array([t_stop])

            seg_kw: dict = dict(method=self.method, t_eval=seg_eval, rtol=self.rtol, atol=self.atol)
            if self.dtmax is not None:
                seg_kw["max_step"] = self.dtmax
            sol = solve_ivp(rhs, (t_cur, t_stop), x_cur, **seg_kw)
            if not sol.success:
                elapsed_ms = (time.perf_counter() - t0_wall) * 1000
                _log.error("segment solve failed at t=%.6f after %.0f ms: %s", t_stop, elapsed_ms, sol.message)
                raise RuntimeError(f"Solver failed at t={t_stop:.6f}: {sol.message}")

            # Collect — drop the first point if it duplicates the last saved point
            t_seg = sol.t
            x_seg = sol.y
            if all_t and len(t_seg) > 0 and abs(t_seg[0] - all_t[-1][-1]) < 1e-15:
                t_seg = t_seg[1:]
                x_seg = x_seg[:, 1:]
            if len(t_seg) > 0:
                all_t.append(t_seg)
                all_x.append(x_seg)

            x_cur = sol.y[:, -1].copy()
            t_cur = t_stop

            # Fire callbacks at this tstop
            for cb in cb_at.get(t_stop, []):
                updates = cb.python_fn(t_stop, x_cur, p, compiled_spec)
                if updates:
                    for key, val in updates.items():
                        if key in compiled_spec.state_index_map:
                            s, e = compiled_spec.state_index_map[key]
                            x_cur[s:e] = np.atleast_1d(val) if e - s > 1 else val
                        else:
                            raise KeyError(
                                f"Callback '{cb.name}' returned unknown state key '{key}'. "
                                f"Available: {list(compiled_spec.state_index_map)}"
                            )
                _log.debug("callback '%s' fired at t=%.6f", cb.name, t_stop)

            if pbar is not None:
                pbar.update(t_stop - (all_boundaries[all_boundaries.index(t_stop) - 1] if all_boundaries.index(t_stop) > 0 else t0_sim))

        if pbar is not None:
            pbar.close()

        elapsed_ms = (time.perf_counter() - t0_wall) * 1000
        _log.debug("segmented solve done in %.1f ms, %d segments", elapsed_ms, len(all_t))

        t_out = np.concatenate(all_t) if all_t else np.array([t0_sim])
        x_out = np.concatenate(all_x, axis=1) if all_x else np.array(compiled_spec.x0)[:, None]
        return SolveResult(t=t_out, x=x_out)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _apply_save_density(
    t_eval: "np.ndarray | None",
    tspan: tuple[float, float],
    dtsave: "float | None",
    n_save_points: int,
) -> "np.ndarray | None":
    """Convert dtsave / n_save_points to a t_eval array if the caller didn't supply one."""
    if t_eval is not None:
        return t_eval   # explicit t_eval wins
    t0, tf = tspan
    if dtsave is not None and dtsave > 0.0:
        return np.arange(t0, tf + dtsave * 0.5, dtsave)
    if n_save_points > 0:
        return np.linspace(t0, tf, n_save_points)
    return None


def _merge_t_eval(
    t_eval: "np.ndarray | None",
    tstops: list[float],
) -> "np.ndarray | None":
    if t_eval is not None:
        return np.sort(np.unique(np.concatenate([t_eval, tstops]))) if tstops else t_eval
    return np.array(tstops) if tstops else None


def _wrap_rhs_progress(rhs, t0: float, tf: float):
    try:
        from tqdm.auto import tqdm
    except ImportError:
        return rhs
    duration = tf - t0
    pbar = tqdm(
        total=duration, unit="s", desc="scipy",
        bar_format="{desc}: {percentage:.0f}%|{bar}| {n:.3g}/{total:.3g} s  [{elapsed}<{remaining}]",
        dynamic_ncols=True,
    )
    last_t = [t0]

    def rhs_tracked(t: float, x):
        if t > last_t[0]:
            pbar.update(t - last_t[0])
            last_t[0] = t
        return rhs(t, x)

    rhs_tracked._pbar = pbar
    return rhs_tracked


def _close_rhs_progress(rhs_tracked) -> None:
    pbar = getattr(rhs_tracked, "_pbar", None)
    if pbar is not None:
        pbar.close()
